swagger: "2.0"
info:
  version: "1.0.0"
  title: "merida"
tags:
  - name: "posts"
    description: "Functions related to posts"
paths:
  /posts:
    post:
      summary: "Create new Post"
      description: "Creates a new Post on merida db"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Information required to create the post"
        required: true
        schema:
          $ref: "#/definitions/CreatePost"
      responses:
        201: 
          description: "Success"
          schema:
            $ref: "#/definitions/Post"
        500:
          description: "Internal Server Error while creating posts"
      tags:
        - "posts"
  /posts/{id}:
    get:
      summary: "Get a post"
      description: "Fetch attributes of a post, which is founded using its id"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: id
        type: string
        required: true
      responses:
        200: 
          description: "Success"
          schema:
            $ref: "#/definitions/Post"
        500:
          description: "Internal Server Error while fetching post"
      tags:
        - "posts"
    put:
      summary: "Update a post"
      description: "Update the content of a post"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: id
        type: string
        required: true
      - in: body
        name: newContent
        required: true
        schema:
          $ref: "#/definitions/NewContent"
      responses:
        200: 
          description: "Success"
          schema:
            $ref: "#/definitions/Post"
        500:
          description: "Internal Server Error while updating post"
      tags:
        - "posts"
    delete:
      summary: "Delete a post"
      description: "Remove post from merida db"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: id
        type: string
        required: true
      responses:
        200: 
          description: "Success"
          schema:
            $ref: "#/definitions/Post"
        500:
          description: "Internal Server Error while deleting post"
      tags:
        - "posts"
  /creator/{creatorId}:
    get:
      summary: "Get a list of posts"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: creatorId
        type: string
        required: true
      responses:
        200: 
          description: "Success"
          schema:
            $ref: "#/definitions/PostArray"
        500:
          description: "Internal Server Error while fetching post"
      tags:
        - "posts"

definitions:
  Post:
    type: object
    properties:
      id:
        type: string
      createdAt:
        type: string
        format: date-time
      idCreator:
        type: string
      content:
        type: string
  CreatePost:
    type: object
    properties:
      idCreator:
        type: string
      content:
        type: string
  NewContent:
    type: object
    properties:
      newContent:
        type: string
  PostArray:
    type: array
    items:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
          format: date-time
        idCreator:
          type: string
        content:
          type: string