version: '3'

services:
  mongodb:
    image: bitnami/mongodb:4.0.9
    container_name: meridaMongodb
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb_data:/bitnami'
    environment:
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGO_DATABASE=merida
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=localhost

volumes:
  mongodb_data: