version: '3.3'

services:
  mongo:
    image: mongo
    ports:
      - '27018:27017'

  merida:
    build: .
    ports:
      - '3002:3002'
    environment:
      - MONGO_DB_URL=mongodb://mongo:27017/merida
      - WAIT_HOSTS= mongo:27017
    links:
      - mongo
    depends_on:
      - mongo