version: '3'

services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'

  merida:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGO_DB_URL=mongodb://mongo:27017/merida
    depends_on:
      - mongo
    command: bash -c "node build/Server.js"